services:
  redpanda-1:
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.8
    container_name: redpanda-1
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '1'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda-1:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda-1:28082,OUTSIDE://localhost:8082
      - --rpc-addr
      - 0.0.0.0:33145
      - --advertise-rpc-addr
      - redpanda-1:33145
    ports:
      - 8082:8082
      - 9092:9092
      - 28082:28082
      - 29092:29092
    volumes:
      - redpanda1-data:/var/lib/redpanda
    networks:
      - realtimeanalytics

  redpanda-2:
     image: docker.redpanda.com/redpandadata/redpanda:v23.1.8
     container_name: redpanda-2
     command:
       - redpanda
       - start
       - --smp
       - '1'
       - --reserve-memory
       - 0M
       - --overprovisioned
       - --node-id
       - '2'
       - --seeds
       - redpanda-1:33145
       - --kafka-addr
       - PLAINTEXT://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
       - --advertise-kafka-addr
       - PLAINTEXT://redpanda-2:29093,OUTSIDE://localhost:9093
       - --pandaproxy-addr
       - PLAINTEXT://0.0.0.0:28083,OUTSIDE://0.0.0.0:8083
       - --advertise-pandaproxy-addr
       - PLAINTEXT://redpanda-2:28083,OUTSIDE://localhost:8083
       - --rpc-addr
       - 0.0.0.0:33146
       - --advertise-rpc-addr
       - redpanda-2:33146
     ports:
       - 8083:8083
       - 9093:9093
       - 28083:28083
       - 29093:29093
     volumes:
       - redpanda2-data:/var/lib/redpanda
     networks:
       - realtimeanalytics

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.2.4
    container_name: redpanda-console
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-1:29092", "redpanda-2:29092"]
          schemaRegistry:
            enabled: false
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-1:9644", "http://redpanda-2:9644"]
        connect:
          enabled: false
    ports:
      - 8080:8080
    depends_on:
      - redpanda-1
      - redpanda-2
    networks:
      - realtimeanalytics

  # Flink cluster
  jobmanager:
    container_name: jobmanager
    build:
      context: .
      dockerfile: Dockerfile-sql
    ports:
      - 8081:8081
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.bind-host: 0.0.0.0
        rest.address: jobmanager
        rest.bind-address: 0.0.0.0
    networks:
      - realtimeanalytics

  taskmanager:
    container_name: taskmanager
    build:
      context: .
      dockerfile: Dockerfile-sql
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 20
        taskmanager.bind-host: 0.0.0.0
    networks:
      - realtimeanalytics

  sql-client:
    image: flink:1.19-scala_2.12-java11
    container_name: sql-client
    command: ["bash", "-c", "sleep infinity"]
    stdin_open: true
    tty: true
    depends_on:
      - jobmanager
    volumes:
      - ./sql-client/lib:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    networks:
      - realtimeanalytics

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    ports:
      - 8123:8123
      - 9000:9000
      - 
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
      - ./clickhouse-ddls/base:/clickhouse-ddls/base       
    networks:
      - realtimeanalytics
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    volumes:
      - ./metabase-data:/metabase-data
    depends_on:
      - clickhouse
    restart: always
    networks:
      - realtimeanalytics

volumes:
  redpanda1-data:
  redpanda2-data:
  clickhouse-data:
  clickhouse-logs:
  metabase-data:
networks:
  realtimeanalytics: